spring:

  main:
    allow-bean-definition-overriding: true

  application:
    name: educational-project

  datasource:
    url: jdbc:postgresql://localhost:5432/educational_db
    username: postgres
    password: testtest
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml


cbr:
  url: https://cbr.ru/scripts/XML_daily.asp

