spring:

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  liquibase:
    enabled: false

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: test-currency-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.example.educationalproject.dto.kafka"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

logging:
  level:
    com.example.currency: DEBUG

cbr:
  url: http://localhost:8080/mock/cbr


app:
  kafka:
    topics:
      currency-rate-created: currency-rate-created
      currency-rate-updated: currency-rate-updated
      currency-rate-deleted: currency-rate-deleted